# Python stubs generated by omniidl from ../Backend/src/calculadora.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "CalculadoraApp"
#
__name__ = "CalculadoraApp"
_0_CalculadoraApp = omniORB.openModule("CalculadoraApp", r"../Backend/src/calculadora.idl")
_0_CalculadoraApp__POA = omniORB.openModule("CalculadoraApp__POA", r"../Backend/src/calculadora.idl")


# interface Calculadora
_0_CalculadoraApp._d_Calculadora = (omniORB.tcInternal.tv_objref, "IDL:CalculadoraApp/Calculadora:1.0", "Calculadora")
omniORB.typeMapping["IDL:CalculadoraApp/Calculadora:1.0"] = _0_CalculadoraApp._d_Calculadora
_0_CalculadoraApp.Calculadora = omniORB.newEmptyClass()
class Calculadora :
    _NP_RepositoryId = _0_CalculadoraApp._d_Calculadora[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_CalculadoraApp.Calculadora = Calculadora
_0_CalculadoraApp._tc_Calculadora = omniORB.tcInternal.createTypeCode(_0_CalculadoraApp._d_Calculadora)
omniORB.registerType(Calculadora._NP_RepositoryId, _0_CalculadoraApp._d_Calculadora, _0_CalculadoraApp._tc_Calculadora)

# Calculadora operations and attributes
Calculadora._d_adicao = ((omniORB.tcInternal.tv_double, omniORB.tcInternal.tv_double), (omniORB.tcInternal.tv_double, ), None)
Calculadora._d_subtracao = ((omniORB.tcInternal.tv_double, omniORB.tcInternal.tv_double), (omniORB.tcInternal.tv_double, ), None)
Calculadora._d_multiplicacao = ((omniORB.tcInternal.tv_double, omniORB.tcInternal.tv_double), (omniORB.tcInternal.tv_double, ), None)
Calculadora._d_divisao = ((omniORB.tcInternal.tv_double, omniORB.tcInternal.tv_double), (omniORB.tcInternal.tv_double, ), None)

# Calculadora object reference
class _objref_Calculadora (CORBA.Object):
    _NP_RepositoryId = Calculadora._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def adicao(self, *args):
        return self._obj.invoke("adicao", _0_CalculadoraApp.Calculadora._d_adicao, args)

    def subtracao(self, *args):
        return self._obj.invoke("subtracao", _0_CalculadoraApp.Calculadora._d_subtracao, args)

    def multiplicacao(self, *args):
        return self._obj.invoke("multiplicacao", _0_CalculadoraApp.Calculadora._d_multiplicacao, args)

    def divisao(self, *args):
        return self._obj.invoke("divisao", _0_CalculadoraApp.Calculadora._d_divisao, args)

omniORB.registerObjref(Calculadora._NP_RepositoryId, _objref_Calculadora)
_0_CalculadoraApp._objref_Calculadora = _objref_Calculadora
del Calculadora, _objref_Calculadora

# Calculadora skeleton
__name__ = "CalculadoraApp__POA"
class Calculadora (PortableServer.Servant):
    _NP_RepositoryId = _0_CalculadoraApp.Calculadora._NP_RepositoryId


    _omni_op_d = {"adicao": _0_CalculadoraApp.Calculadora._d_adicao, "subtracao": _0_CalculadoraApp.Calculadora._d_subtracao, "multiplicacao": _0_CalculadoraApp.Calculadora._d_multiplicacao, "divisao": _0_CalculadoraApp.Calculadora._d_divisao}

Calculadora._omni_skeleton = Calculadora
_0_CalculadoraApp__POA.Calculadora = Calculadora
omniORB.registerSkeleton(Calculadora._NP_RepositoryId, Calculadora)
del Calculadora
__name__ = "CalculadoraApp"

#
# End of module "CalculadoraApp"
#
__name__ = "calculadora_idl"

_exported_modules = ( "CalculadoraApp", )

# The end.
