package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculadora.idl
* Monday, 14 September 2026 18:12:23 o'clock CAT
*/

public interface CalculadoraOperations 
{

  //Declaracao dos metodos da interface
  double adicao (double a, double b);
  double subtracao (double a, double b);
  double multiplicacao (double a, double b);
  double divisao (double a, double b);
} // interface CalculadoraOperations
