# DO NOT EDIT THIS FILE!
#
# Python module CalculadoraApp__POA generated by omniidl

import omniORB
omniORB.updateModule("CalculadoraApp__POA")

# ** 1. Stub files contributing to this module
import calculadora_idl

# ** 2. Sub-modules

# ** 3. End
